In [1]:
from tensorflow.keras.models import load_model
import tensorflow as tf
import numpy as np
import pandas as pd

In [2]:
nn = load_model('heart.keras')
df = pd.read_csv('heart.csv')
df

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [3]:
df['RestingECG'].value_counts()

RestingECG
Normal    552
LVH       188
ST        178
Name: count, dtype: int64

In [4]:
# Use a sample input with the expected number of features (16)
# Columns: Age, Sex, RestingBP, Cholesterol, FastingBS, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, ChestPainType_ASY, ChestPainType_ATA, ChestPainType_NAP, ChestPainType_TA, RestingECG_LVH, RestingECG_Normal, RestingECG_ST
sample_input = np.array([[40, 1, 140, 289, 0, 172, 0, 0.0, 2, 0, 0, 0, 1, 0, 0, 0]]).astype(float)
display(sample_input)
# print(nn.predict(sample_input))

if nn.predict(sample_input)[0][0] > 0:
    print('Have Heart Disease')
else: 
    print("Dont have heart disease")

array([[ 40.,   1., 140., 289.,   0., 172.,   0.,   0.,   2.,   0.,   0.,
          0.,   1.,   0.,   0.,   0.]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
Have Heart Disease

In [5]:
cleanData = pd.read_csv('cleanedDataFrame.csv')
sample_input = cleanData.sample()
sample_input.drop(['HeartDisease'], axis=1, inplace=True)
display(sample_input)
if nn.predict(sample_input)[0][0] > 0:
    print('Have Heart Disease')
else: 
    print("Dont have heart disease")

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST
600,0.3701,0.515952,-0.129513,0.07501,-0.551341,-1.603734,-1.214246,0.105664,-0.596078,-0.481887,-0.532838,-0.229679,-0.507478,-1.228087,2.038947,0.0

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
Have Heart Disease

In [6]:
print(df["ExerciseAngina"].value_counts())
print(df["ExerciseAngina"].unique())

ExerciseAngina
N    547
Y    371
Name: count, dtype: int64
<ArrowStringArray>
['N', 'Y']
Length: 2, dtype: str

In [7]:
print(df["ST_Slope"].unique())

<ArrowStringArray>
['Up', 'Flat', 'Down']
Length: 3, dtype: str

NameError: name 'X' is not defined